#!/bin/bash

mode=$1

case "$mode" in
    install)
        # Run npm install and suppress the extra output
        npm install > /dev/null 2>&1

        # Check if npm install succeeded
        if [ $? -ne 0 ]; then
            echo "Error occurred during 'npm install'."
            exit 1
        else
            dep_count=$(node -p "Object.keys({...require('./package.json').dependencies, ...require('./package.json').devDependencies} || {}).length")
            echo "$dep_count dependencies installed..."

            npx tsc

            if [ $? -ne 0 ]; then
                echo "A problem occurred while compiling TypeScript."
                exit 1
            fi
        fi
        exit 0
        ;;
    test)
        npx vitest --run --coverage --reporter=json > testResults.json
        npx tsc
        node ./dist/Index.js test
        ;;
    *)
        npx tsc
        if [ -f "$1" ]; then
            node ./dist/Index.js "$1"
            exit 0
        else
            echo "file doesn't exist"
            exit 1
        fi
        ;;
esac
