#!/bin/bash

echo "the script begins to run"
mode=$1
npx tsc

if [ $? -ne 0 ]; then
    echo "A problem in compiling typescript"
else
    echo "Compiling typescript is done Successfully";
fi

case "$mode" in
    install)
        node ./dist/Index.js install
        ;;
    test)
        node ./dist/Index.js test
        ;;
    *)
        if [ -f "$mode" ]; then
            node ./dist/Index.js "$mode"
        else 
            echo "file doesn't exist"
        fi
esac





