#!/bin/bash

echo "the script begins to run"
mode=$1

case "$mode" in
    install)
        npm install
        npx tsc

        if [ $? -ne 0 ]; then
            echo "A problem in compiling typescript"
        else
            echo "Compiling typescript is done Successfully";
        fi
        ;;
    test)
        npx vitest --run --coverage --reporter=json > testResults.json
        npx tsc
        node dist/CleanTestResults.js
        node dist/ProcessTestResults.js     
        ;;
    *)
        npx tsc
        if [ -f "$1" ]; then
            node ./dist/Index.js "$1"
        else 
            echo "file doesn't exist"
        fi
esac




