name: Deploy to EC2 using CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip codebase
      run: zip -r app.zip .

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp app.zip s3://codepipeline-us-east-2-701044401608/app.zip --region us-east-2

    - name: Trigger CodeDeploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
          --application-name Phase-2-Server-App \
          --deployment-group-name Phase-2-Server-App \
          --s3-location bucket=codepipeline-us-east-2-701044401608,key=app.zip,bundleType=zip \
          --region us-east-2
